tosccolors/nsm-addons

nsm_sale_advertising_order/__init__.py
nsm_sale_advertising_order/__manifest__.py
nsm_sale_advertising_order/models/__init__.py
nsm_sale_advertising_order/models/advertising_issue.py
nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/views/advertising_issue_view.xml
nsm_sale_advertising_order/views/sale_advertising_view.xml

Merge Task T0001 to T0006

---

nsm_supplier_portal/models/account_invoice.py

Task link: http://localhost:8090/web?debug=1#id=1&view_type=form&model=account.invoice&menu_id=123&action=202
Module: nsm_supplier_portal.

Task: T0024 - Status in vendor invoice portal

---

nsm_supplier_portal/wizard/portal_wizard.py

Fixed NameError

---

nsm_supplier_portal/models/account_analytic.py
nsm_supplier_portal/models/product.py
nsm_supplier_portal/views/account_analytic_view.xml
nsm_supplier_portal/views/product_view.xml
nsm_supplier_portal/wizard/portal_wizard.py

Task link: https://bo-test.magnus.nl/web#id=46&view_type=form&model=project.task&menu_id=93&action=143
Module: nsm_supplier_portal.

T0033 - Computed fields supp_analytic_accids and supp_category_ids remain empty

---

nsm_account_invoice_2step_validation/__manifest__.py

Task: T0008, second commit, added dependency

---

nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/views/sale_advertising_view.xml

Task:T0025

---

nsm_supplier_portal/models/account_invoice.py
nsm_supplier_portal/views/account_invoice_view.xml

Task:T0040

---

nsm_crm/__init__.py
nsm_crm/__manifest__.py
nsm_crm/controllers/__init__.py
nsm_crm/controllers/controllers.py
nsm_crm/demo/demo.xml
nsm_crm/models/__init__.py
nsm_crm/models/res_partner.py
nsm_crm/security/ir.model.access.csv
nsm_crm/views/res_partner_view.xml

Task:T0043

---

nsm_sale_advertising_order/models/sale_advertising.py

Task link: https://bo-test.magnus.nl/web#id=40&view_type=form&model=project.task&action=143

Task: T0027 - Create a domain on showing product_template_id in sale.advertising.order.line

---

nsm_sale_advertising_order/__manifest__.py
nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/views/sale_advertising_view.xml

Updated material_id and mapping_remarks

Task: T0068, Updated material_id and mapping_remarks

---

nsm_sale_advertising_order/views/sale_advertising_view.xml

Task: T0068, Indeellijst excel report

---

nsm_sale_advertising_order/report/report_indeellijst_list.py

Added column Material ID in report

Task: T0068,Added column Material ID in report

---

nsm_sale_advertising_order/report/report_indeellijst_list.py

Additional changes like remove title & issue code, print qty if > 1 etc.

Task: T0068, Additional changes like remove title & issue code, print qty if > 1 etc.

---

nsm_sale_advertising_order/__manifest__.py
nsm_sale_advertising_order/data/circulation_type.xml
nsm_sale_advertising_order/i18n/nl.po
nsm_sale_advertising_order/models/__init__.py
nsm_sale_advertising_order/models/circulation_type.py
nsm_sale_advertising_order/models/product.py
nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/views/circulation_type_view.xml
nsm_sale_advertising_order/views/menuitem.xml
nsm_sale_advertising_order/views/product_view.xml
nsm_sale_advertising_order/views/sale_advertising_view.xml

Task: T0085 - Pluspropositions

Task: T0085 - Pluspropositions

---

nsm_sale_advertising_order/__manifest__.py
nsm_sale_advertising_order/security/ir.model.access.csv
nsm_sale_advertising_order/views/sale_advertising_view.xml

Task: T0085, Feedback Commits

---

nsm_ad4all_soap/models/sale_advertising.py

Task: nsm_ad4all_soap preserve XML Structure
Module: nsm_ad4all_soap

Task: nsm_ad4all_soap preserve XML Structure

---

nsm_ad4all_soap/models/sale_advertising.py

Task: Remove Item tags from nsm_ad4all_soap XML Structure

---

nsm_ad4all_soap/models/sale_advertising.py

Bug Fixing nsm_ad4all_soap XML Structure
Module: nsm_ad4all_soap

Bug Fixing nsm_ad4all_soap XML Structure

---

nsm_ad4all_soap/models/sale_advertising.py

Task: bug Fix nsm_ad4all_soap XML Structure

---

nsm_account/report/report_invoice.xml

Task: Remove IBAN attribute from nsm invoice report
Module: nsm_account

Task: Remove IBAN attribute from nsm invoice report

---

freelancer_self_billing/__manifest__.py
freelancer_self_billing/report/report_invoice_hon.xml
freelancer_self_billing/views/account_invoice_report.xml

Module: freelancer_self_billing

NSM HON Invoice report migrating RML to QWEB

---

freelancer_self_billing/report/report_invoice_hon.xml

Module: freelancer_self_billing.

Task: NSM HON Invoice report migrating RML to QWEB (second commit)

---

freelancer_self_billing/report/report_invoice_hon.xml

Module: freelancer_self_billing.

Task: NSM HON Invoice report migrating RML to QWEB (third commit)

---

nsm_sale_advertising_order/report/report_indeellijst_list.py
nsm_sale_advertising_order/views/sale_advertising_view.xml

Task: T0075 - Additions to Indeellijst NSM

---

nsm_expense/models/hr_expense.py
nsm_expense/views/hr_expense_view.xml

Task: T0122 - Expenses statuses bug fix
Module: nsm_expense

T0122 - Expenses statuses bug fix

---

nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/views/sale_advertising_view.xml

Task: T0095 - Set domain on recurring ads in advertising.sale.order.line, show sale.advertising.issue_name

---

nsm_account/i18n/nl.po
nsm_account/report/report_invoice.xml

Task: T0125 - nsm sale invoice layout (Second commit)

---

freelancer_self_billing/report/report_invoice_hon.xml
nsm_account/i18n/nl.po
nsm_account/report/report_invoice.xml

Modules: nsm_account, freelancer_self_billing.

Task: T0125 - nsm sale invoice layout (Third commit).

---

nsm_account/__manifest__.py
nsm_account/views/report.xml

Modules: nsm_account.
Note: Updated Margin Top and Header Spacing.

Task: T0125 - nsm sale invoice layout (Fourth commit).

---

nsm_sale_advertising_order/report/report_saleorder.xml

Modules: nsm_sale_advertising_order.
Note: Updated the followings as per Skype call, removed colon in the header, replaced Description with Reference and updated widths.

Task: T0094 - Create customised NSM sale order reports (incl Package order reports)

---

nsm_account/report/report_invoice.xml
nsm_package_account/__init__.py
nsm_package_account/__manifest__.py
nsm_package_account/controllers/__init__.py
nsm_package_account/controllers/controllers.py
nsm_package_account/demo/demo.xml
nsm_package_account/models/__init__.py
nsm_package_account/models/models.py
nsm_package_account/report/report_invoice.xml
nsm_package_account/security/ir.model.access.csv
nsm_package_account/views/templates.xml
nsm_package_account/views/views.xml
nsm_package_sale/__init__.py
nsm_package_sale/__manifest__.py
nsm_package_sale/controllers/__init__.py
nsm_package_sale/controllers/controllers.py
nsm_package_sale/demo/demo.xml
nsm_package_sale/models/__init__.py
nsm_package_sale/models/models.py
nsm_package_sale/report/report_saleorder.xml
nsm_package_sale/security/ir.model.access.csv
nsm_package_sale/views/templates.xml
nsm_package_sale/views/views.xml
nsm_sale_advertising_order/report/report_saleorder.xml

Modules: nsm_sale_advertising_order, nsm_account, nsm_package_sale & nsm_package_account.
Note: This commit includes first point of this task.

Task: T0055 - Create package boolean in sale.order (regular sales module)

---

nsm_account_invoice_2step_validation/models/account_invoice.py

Module: nsm_account_invoice_2step_validation.

Task: T0129 - team_id disappears after adjusting account.invoice

---

nsm_supplier_portal/__manifest__.py
nsm_supplier_portal/views/account_invoice_view.xml

T0144 - payment_mode_id on account.invoice

---

nsm_sale_advertising_order/report/report_saleorder.xml

Task: T0127 - Changes NSM advertising sale order report

---

nsm_sale_advertising_order/report/report_credit_control_summary.xml

Task: T0148 - NSM Credit control mail/letter text

---

nsm_account_invoice_2step_validation/views/account_invoice_view.xml

Module: nsm_account_invoice_2step_validation.

T0140 - Product domain: boolean purchase_ok = True

---

nsm_sale_advertising_order/models/sale_advertising.py

T0124 - Action 'create multiple lines' on button 'approval sales mgr' (& after 'confirm')

T0124 - Action 'create multiple lines' on button 'approval sales mgr' (& after 'confirm')

---

nsm_package_account/report/report_invoice.xml

T0150 - Issue of no invoice lines in Invoice report

---

nsm_sale_advertising_order/report/report_credit_control_summary.xml

Task: T0148 - NSM Credit control mail/letter text (second commit)

---

nsm_supplier_portal/views/account_invoice_view.xml

Task: T0153 - View for portal user too much

---

nsm_sale_advertising_order/models/sale_advertising.py

T0027 - Create a domain on showing product_template_id in sale.advertising.order.line

---

nsm_account/report/report_invoice.xml

Module: nsm_account.
Note: Fixed the issue of "IndexError: tuple index out of range".

Task: T0125 - nsm sale invoice layout

---

nsm_sale_advertising_order/report/report_saleorder.xml

T0127 - Changes NSM advertising sale order report

---

nsm_account_invoice_2step_validation/views/res_partner_view.xml

Module: nsm_account_invoice_2step_validation.

Task: T0152 - team_id on res.partner not mandatory for supplier=true

---

nsm_sale_advertising_order/__manifest__.py
nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/wizard/__init__.py
nsm_sale_advertising_order/wizard/adv_line_invoice.py
nsm_supplier_portal/views/account_invoice_view.xml

Task: T0155 - T0153 for Edition selection
Module: nsm_supplier_portal

 Task: T0155 - T0153 for Edition selection

---

nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/views/sale_advertising_view.xml

Task: T0172 - Bug fix domain sale.advertising.order.line

---

nsm_sale_advertising_order/__manifest__.py
nsm_sale_advertising_order/models/__init__.py
nsm_sale_advertising_order/models/proof_delivery_list.py
nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/report/nsm_report.xml
nsm_sale_advertising_order/report/report_pndl_delivery_list.py
nsm_sale_advertising_order/views/menuitem.xml
nsm_sale_advertising_order/views/proof_delivery_list_view.xml
nsm_sale_advertising_order/views/sale_advertising_view.xml

Task: T0176 - Bug fix proof number delivery list

Task: T0176 - Bug fix proof number delivery list

---

nsm_account/report/report_invoice.xml

T0179 - S.B.A.D. + Disc. (%) columns in account.invoice report

---

nsm_sale_advertising_order/models/sale_advertising.py

Note: This commit makes sure the status of the SO doesn't change when click on "Print" button and "Send by Email" button.

T0162 - Bug fix: in sale.advertising.order form, status of the sale order moves to "Quotation sent" when I click the "Print" button.

---

nsm_sale_advertising_order/security/ir.model.access.csv

Task: T0176 - Added Access Security for proof.number.delivery.list

Task: T0176 - Added Access Security for proof.number.delivery.list

---

nsm_account/report/report_invoice.xml

Task: T0182 - Invoice update on 6th March

---

nsm_sale_advertising_order/models/proof_delivery_list.py
nsm_sale_advertising_order/models/sale_advertising.py
nsm_sale_advertising_order/report/report_pndl_delivery_list.py
nsm_sale_advertising_order/views/sale_advertising_view.xml

T0188 - Issue fix proof_number_payer type

---

nsm_account/report/report_invoice.xml
nsm_account/views/account_invoice_view.xml
nsm_sale_advertising_order/report/report_saleorder.xml
nsm_sale_advertising_order/views/sale_advertising_view.xml

Modules: nsm_account, nsm_sale_advertising_order.

T0183 - NSM - sale order & invoice report improvements

---

nsm_sale_advertising_order/models/sale_advertising.py

 T0172 - Bug fix domain sale.advertising.order.line (Update on March 11)

---

nsm_supplier_portal/views/account_invoice_view.xml

T0184 - Edit Formview: Supplier Portal invoice 'reference' fill

---

nsm_sale_advertising_order/models/sale_advertising.py

Note: Updated lable for proof_number_payer_id and removed proof_number_payer from advanced search filter.

Task: T0188 - Issue fix proof_number_payer type

---

nsm_supplier_portal/views/portal_wizard_view.xml
nsm_supplier_portal/wizard/portal_wizard.py

T0193 - Portal Access Mgmt Wizard OU-update

---

nsm_custom_view_accounting/__init__.py
nsm_custom_view_accounting/__manifest__.py
nsm_custom_view_accounting/controllers/__init__.py
nsm_custom_view_accounting/controllers/controllers.py
nsm_custom_view_accounting/demo/demo.xml
nsm_custom_view_accounting/i18n/nl.po
nsm_custom_view_accounting/models/__init__.py
nsm_custom_view_accounting/models/models.py
nsm_custom_view_accounting/security/ir.model.access.csv
nsm_custom_view_accounting/views/account_invoice_view.xml

Module: nsm_custom_view_accounting.

Task: T0195 - Changes invoice views

---

nsm_ad4all_soap/i18n/nl.po
nsm_sale_advertising_order/i18n/nl.po
nsm_sale_advertising_order/views/sale_advertising_view.xml

Modules: nsm_sale_advertising_order, nsm_ad4all_soap.

T0196 - Changes sale order view

---

nsm_account/__manifest__.py
nsm_account/views/account_invoice_view.xml

T0197 - Changes invoice views part 2

---

nsm_sale_advertising_order/i18n/nl.po
nsm_sale_advertising_order/views/sale_advertising_view.xml

T0196 - Changes sale order view (fixed the translation issue of proof_number_adv_customer)

---

nsm_sale_advertising_order/report/report_saleorder.xml

T0166 - Computed discount on order/invoice report NSM (condition to display Computed discount in total area)

---

nsm_sale/__init__.py
nsm_sale/__manifest__.py
nsm_sale/controllers/__init__.py
nsm_sale/controllers/controllers.py
nsm_sale/data/mail_template_data.xml
nsm_sale/demo/demo.xml
nsm_sale/models/__init__.py
nsm_sale/models/models.py
nsm_sale/security/ir.model.access.csv
nsm_sale/views/templates.xml
nsm_sale/views/views.xml

T0181 - Add NSM Sale Order Notification Email template to module

---

nsm_sale_advertising_order/data/data.xml

T0180 - Add NSM Advertising Sales Order - Send by Email template to module

---

nsm_supplier_portal/models/account_invoice.py

T0143 - Verification total check action

---

nsm_custom_view_sales/views/nsm_adv_order_line_tree_view.xml
nsm_disable_follower_mails/views/mail_followers_config_view.xml

Small textual changes in mail_followers_config view.

Small textual changes in mail_followers_config view.

---

nsm_sale_advertising_order/views/sale_advertising_view.xml
nsm_tree_many2one_clickable/__init__.py
nsm_tree_many2one_clickable/__manifest__.py
nsm_tree_many2one_clickable/controllers/__init__.py
nsm_tree_many2one_clickable/controllers/controllers.py
nsm_tree_many2one_clickable/demo/demo.xml
nsm_tree_many2one_clickable/models/__init__.py
nsm_tree_many2one_clickable/models/models.py
nsm_tree_many2one_clickable/security/ir.model.access.csv
nsm_tree_many2one_clickable/views/sale_advertising_view.xml

T0146 - Order reference in Indeellijst should be clickable
Module: nsm_tree_many2one_clickable

 T0146 - Order reference in Indeellijst should be clickable

---

nsm_account_access/views/account_menuitem.xml
nsm_custom_view_sales/__init__.py
nsm_custom_view_sales/__manifest__.py
nsm_custom_view_sales/views/nsm_adv_order_line_tree_view.xml

Added new group by filter for analytic account
Module: nsm_account_access

Added new group by filter for analytic account

---

nsm_crm/views/res_partner_view.xml
nsm_custom_view_sales/views/nsm_adv_order_line_tree_view.xml

nsm_custom_view_sales: T0248 - Removed some fields due to duplicates in inherited view.

nsm_custom_view_sales: T0248 - Removed some fields due to duplicates in inherited view.

---

nsm_sale_advertising_order/report/report_saleorder.xml

nsm_sale_advertising_order : T0280 - Change ad_class date_type in report_saleorder

nsm_sale_advertising_order : T0280 - Change ad_class date_type in report_saleorder

---

nsm_sale_advertising_order/report/report_credit_control_summary.xml

T0284 - Misset invoice layout and credit control layout changes

T0284 - Misset invoice layout and credit control layout changes

---

nsm_account/models/account.py
nsm_account_access/__init__.py
nsm_account_access/models/__init__.py
nsm_account_access/models/analytic.py
nsm_account_access/wizard/__init__.py
nsm_account_access/wizard/account_invoice_refund.py

T0273 - Authorizations for NSM Part-2 & fully invoiced fixed for refund
Module: nsm_account_access

T0273 - Authorizations for NSM Part-2 & fully invoiced fixed for refund

---

nsm_crm/__manifest__.py
nsm_crm/views/res_partner_view.xml

nsm_crm: T0247 - Changes in Customers TreeView for NSM - Bug fix

nsm_crm: T0247 - Changes in Customers TreeView for NSM - Bug fix

---

nsm_crm/__manifest__.py
nsm_crm/views/res_partner_view.xml

nsm_crm: T0247 - Changes in Customers TreeView for NSM. Nog een keertje

nsm_crm: T0247 - Changes in Customers TreeView for NSM. Nog een keertje

---

nsm_account_access/__manifest__.py
nsm_account_access/views/account_invoice_view.xml

T0307 - NSM form view field access group
Module: nsm_account_access

T0307 - NSM form view field access group

---

nsm_ad4all_soap/models/sale_advertising.py
nsm_sale_advertising_order/models/sale_advertising.py

Task T0275 - Show sale.order.line ID in recurring_id many2one selection field when setting recurring_id.

Task T0275 - Show sale.order.line ID in recurring_id many2one selection field when setting recurring_id.

---

nsm_account/report/report_invoice.xml

Task T0306 - Remove standard Odoo footer from package sale order report
Module: nsm_account

T0306 - Remove standard Odoo footer from package sale order report

---

nsm_account/models/account_invoice.py

T0168 - Bug fix: Error message on "Print" button in account.invoice view
Module: nsm_account

T0168 - Bug fix: Error message on "Print" button in account.invoice view

---

nsm_account/__manifest__.py
nsm_account/views/account_invoice_view.xml
nsm_account/views/sale_view.xml

T0408 - Issue 23 - Sales order & Invoice form view - operating unit Id

---

nsm_sale_advertising_order/views/sale_advertising_view.xml

T0412 - Issue 20 - Start & End date mandatory in advertising sales order

---

nsm_sale_advertising_order/views/sale_advertising_view.xml

Note:This task been merge with T0320

Reverted T0412 - Issue 20 - Start & End date mandatory in advertising sales order

---

nsm_account_invoice_2step_validation/views/account_invoice_view.xml

Added authorize and verification group for account_id into account.invoice.line
Module: nsm_account_invoice_2step_validation

Added authorize and verification group for account_id into account.invoice.line

---

nsm_sale_advertising_order/report/report_pndl_delivery_list.py

module: nsm_sale_advertising_order

T0406 - Issue 53 - Change contents of proof number delivery list

---

nsm_custom_view_accounting/views/account_invoice_view.xml

module: nsm_custom_view_accounting

T0433 - Add advertiser to invoice search options

---

nsm_expense/models/hr_expense.py
nsm_expense/views/hr_expense_view.xml
nsm_sale_advertising_order/models/sale_advertising.py

T0432 - Analytic tag copy from magnus expenses to nsm expenses

---

nsm_sale_advertising_order/models/sale_advertising.py

updating onchange function on field advertising_agency
customer_contact field to False

updating onchange function field advertising_agent

---

nsm_account_invoice_2step_validation/__manifest__.py
nsm_account_invoice_2step_validation/models/__init__.py
nsm_account_invoice_2step_validation/models/account_invoice.py
nsm_account_invoice_2step_validation/models/res_company.py
nsm_account_invoice_2step_validation/security/account_security.xml
nsm_account_invoice_2step_validation/views/account_invoice_view.xml
nsm_account_invoice_2step_validation/views/res_company_view.xml
nsm_supplier_portal/models/account_analytic.py
nsm_supplier_portal/models/account_invoice.py
nsm_supplier_portal/views/account_analytic_view.xml
nsm_supplier_portal/views/account_invoice_view.xml
publishing_invoicing/__init__.py
publishing_invoicing/__manifest__.py
publishing_invoicing/models/__init__.py
publishing_invoicing/models/invoicing_property.py
publishing_invoicing/models/res_partner.py
publishing_invoicing/models/sale_order.py
publishing_invoicing/security/ir.model.access.csv
publishing_invoicing/views/invoicing_property_view.xml
publishing_invoicing/views/res_partner_views.xml
publishing_invoicing/views/sale_order_views.xml

New module is created with invoicing property details

T0455-Modify advertising invoicing

---

nsm_account_invoice_2step_validation/views/account_invoice_view.xml
nsm_account_invoice_2step_validation/wizard/payment_order_create.py

Module:nsm_account_invoice_2step_validation

Added: verified by publisher domain & filter Renamed: server action & filter

---

nsm_account_invoice_2step_validation/models/account_invoice.py

Module:nsm_account_invoice_2step_validation

Added filter publisher _write for NSM 

---

nsm_expense/views/hr_expense_view.xml

Expense payment_mode removed radio selection 

---

accounting_interface_roularta/__manifest__.py
accounting_interface_roularta/models/account.py
accounting_interface_roularta/models/roularta_config.py
accounting_interface_roularta/views/roularta_config_view.xml

Added External libraries

---

accounting_interface_roularta/models/account.py
accounting_interface_roularta/models/roularta_config.py
accounting_interface_roularta/views/account_view.xml

Status mapping and view changes

Fix: Refund roularta_sent boolean

---

accounting_interface_roularta/models/account.py
accounting_interface_roularta/views/account_view.xml
nsm_sale_advertising_order/views/sale_advertising_view.xml

2. Added roularta ref to invoice in all cases.
3. Invoice title must be selectable always
4. Date field make it visible.

1. Added partner refrence to invoice.

---

accounting_interface_roularta/__manifest__.py
accounting_interface_roularta/models/__init__.py
accounting_interface_roularta/models/account.py
accounting_interface_roularta/models/advertising_issue.py
accounting_interface_roularta/views/account_view.xml
accounting_interface_roularta/views/sale_advertising_view.xml

2. Added Default Supplier Issue

1. Sync supplier invoice to Roularta transaction when authorized

---

nsm_ad4all_soap/models/sale_advertising.py

2. If Fails, try to send other lines

1. Revert If line sent to interface, don't send again.

---

nsm_ad4all_soap/models/sale_advertising.py

1. Added response message
